name: sketch_classifier_env
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - pip
  - pip:
    - mlflow
    - numpy
    - pillow
    - scikit-image
    - tqdm
    - datasets
    - pyyaml